version: '3.1'

services:
  frontend:
    build: ./frontend
    container_name: cw_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: cw_backend
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb?schema=public
  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080